# Generated by Django 4.2.7 on 2023-11-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assingment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tname', models.CharField(max_length=50)),
                ('T_iD', models.CharField(max_length=50)),
                ('Aname', models.CharField(max_length=50)),
                ('key', models.CharField(max_length=6, unique=True)),
                ('deadline', models.DateTimeField()),
                ('document', models.FileField(upload_to='assignments/')),
            ],
        ),
    ]
