# Generated by Django 4.2.7 on 2023-11-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plag', '0002_remove_assingment_tname'),
    ]

    operations = [
        migrations.AddField(
            model_name='assingment',
            name='Tname',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
