# Generated by Django 4.2.7 on 2023-11-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plag', '0003_assingment_tname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students_Assigments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sname', models.CharField(max_length=50)),
                ('S_iD', models.CharField(max_length=50)),
                ('key', models.CharField(max_length=6, unique=True)),
                ('document', models.FileField(upload_to='Sassignments/')),
            ],
        ),
    ]
