# Generated by Django 4.2.7 on 2023-11-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plag', '0004_students_assigments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students_assigments',
            name='key',
            field=models.CharField(max_length=6),
        ),
    ]
