# Generated by Django 4.2.7 on 2023-11-28 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plag', '0006_auto_20231126_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assingment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='students_assigments',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
